import = [
  "~/.config/alacritty/themes/themes/dracula.toml"
]

[window]
padding = { x = 10, y = 10}

[font]
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
size = 15

# [font]
# size = 17
#
# [font.bold]
# family = ""
#
# [font.bold_italic]
# family = "monospace"
# style = "Bold Italic"
#
# [font.italic]
# family = "monospace"
# style = "Italic"
#
# [font.normal]
# family = "monospace"
# style = "tokyo-night"
